export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_RESEND_FAILURE = 'SIGNUP_RESEND_FAILURE';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_ERROR';
export const VERIFY_RESET_PASSWORD_SUCCESS = 'VERIFY_RESET_PASSWORD_SUCCESS';
export const VERIFY_RESET_PASSWORD_FAILURE = 'VERIFY_RESET_PASSWORD_FAILURE';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER_DETAIL = 'FETCH_USER_DETAIL';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL';
export const ADD_POST = 'ADD_POST';
export const FETCH_CATE = 'FETCH_CATE';

export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODO_DETAIL = 'FETCH_TODO_DETAIL';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
